esphome:
  name: esp01a
  friendly_name: ESP01A

esp8266:
  board: esp01_1m

substitutions:
  device_name: esp01a
  pin_ingebouwdeblauweled : GPIO2   

# Enable logging https://www.forward.com.au/pfod/ESP8266/GPIOpins/ESP_01S.jpg
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "vszRftJMTw1y77gRs3qMGLAAerq0xCC3Eu9saitfTs4="

ota:
  - platform: esphome
    password:  "2ec8e296e53496ccccb705096c6b81bd"


wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password 
  - ssid: !secret wifi_ssid3
    password: !secret wifi_password   

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: "kipkipkip"

captive_portal:


web_server:
  port : 80


mqtt:
  broker: !secret mqtt_broker 
  username: !secret mqtt_user 
  password: !secret mqtt_password  

 
 
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${device_name}_IP"
    ssid:
      name: "${device_name}_ssid"
    bssid:
      name: "${device_name}_bssid"
    mac_address:
      name: "${device_name}_mac"
    scan_results:
      name: "${device_name}_scanresults"
    dns_address:
      name: "${device_name}_dns"   

# blauwe builtin Led
output:
  - platform: gpio
    pin: ${pin_ingebouwdeblauweled} #GPIO2
    id: gpio_2
    inverted: yes
    

 

## blauwe builtin Led op gpio_2
light:
  - platform: binary
    output: gpio_2
    name: esp-builinledBLEU


 


switch:      
  - platform: restart
    name: ${device_name}_restart   

 
# Example configuration entry with 2 sensors and filter
sensor:
#sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "${device_name}_WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 80s
    entity_category: "diagnostic"
    disabled_by_default: true
    internal: true
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "${device_name}_WiFi_Pct"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
  - platform: uptime
    name: "${device_name}_Uptime"   

# Example configuration entry
#sensor:


  - platform: uptime
    name: "${device_name} Uptime"   


