esphome:
  name: "wt32-lan-usbc"
  friendly_name: "wt32-lan-usbc"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

 
ota:
  - platform: esphome
    password: "9f3dcdeb2155ad538b998b1b84cbea5b"


ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN   # or CLK_OUT depending on your board specs
  phy_addr: 1
  power_pin: GPIO16
  id: eth


web_server:
  port: 80 

# Enable Home Assistant API
api:

 

 



 
 